# Generated by Django 4.2.7 on 2024-04-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_file', models.FileField(upload_to='encrypted_files/')),
                ('key', models.BinaryField()),
                ('password', models.BinaryField()),
            ],
        ),
    ]
